require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  prettier: rubocop.yml

Rails:
  Enabled: true

AllCops:
  UseCache: true
  NewCops: enable
  CacheRootDirectory: 'tmp/rubocop'
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
  TargetRubyVersion: 3.1

Style/Documentation:
  Enabled: false

Layout/IndentationWidth:
  Enabled: true

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'db/migrate/*'
    - 'db/**/*'

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 1500

Layout/LineLength:
  Exclude:
    - 'db/migrate/*'
  Max: 140

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
  Max: 20

Style/BlockComments:
  Enabled: true
  Exclude:
    - spec/spec_helper.rb

Style/ConditionalAssignment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Naming/PredicateName:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
