inherit_gem:
  standard: config/base.yml

require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rspec

AllCops:
  UseCache: true
  NewCops: enable
  CacheRootDirectory: "tmp/rubocop"
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "node_modules/**/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "db/migrate/**/*"
    - "config/initializers/content_security_policy.rb"
    - "spec/spec_helper.rb"
  TargetRubyVersion: 3.1
