Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
  TargetRubyVersion: 2.5

Documentation:
  Enabled: false

Layout/IndentationWidth:
  Enabled: true

Lint/PercentStringArray:
  Exclude:
    - config/initializers/secure_headers.rb

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'db/migrate/*'
    - 'db/**/*'

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 1500

Metrics/LineLength:
  Exclude:
    - 'db/migrate/*'
  Max: 140

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
  Max: 20

Style/BlockComments:
  Enabled: true
  Exclude:
    - spec/spec_helper.rb

Style/BracesAroundHashParameters:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Naming/PredicateName:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
