inherit_gem:
  standard: config/base.yml

plugins:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance

AllCops:
  UseCache: true
  NewCops: enable
  CacheRootDirectory: "tmp/rubocop"
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "node_modules/**/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "db/migrate/**/*"
    - "config/initializers/content_security_policy.rb"
    - "spec/spec_helper.rb"
  TargetRubyVersion: 3.1
