x-base: &app_base
  build:
    context: .
    target: dev
  ports:
    - "3000:3000"
  environment:
    DOCKER_CONTAINER: 1
    POSTGRES_DATABASE: app
    POSTGRES_USERNAME: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_URL: postgres
    DISPLAY_ENV: development
  volumes:
    - bundle_cache:/bundle
    - .:/app

services:
  web:
    <<: *app_base
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - s3
      - mailhog
    command: sh ./docker/start.sh
  # worker:
  #   <<: *app_base
  #   command: sh ./docker/start_worker.sh
  #   depends_on:
  #     - web
  # assets:
  #   <<: *app_base
  #   command: bin/vite dev
  #   depends_on:
  #     - web

  s3:
    image: adobe/s3mock
    ports:
      - 3090:9090
      - 3091:9091
    environment:
      initialBuckets: storage
      retainFilesOnExit: "true"
    volumes:
      - s3:/s3mockroot:delegated
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  postgres:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  bundle_cache:
  postgres:
  s3:
