x-base: &app_base
  build:
    context: .
  ports:
    - "3000:3000"
  environment:
    DOCKER_CONTAINER: 1
    POSTGRES_DATABASE: app
    POSTGRES_USERNAME: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_URL: postgres
    DISPLAY_ENV: development
    # VITE_RUBY_HOST: ${VITE_HOST:-vite}
  volumes:
    - bundle_cache:/bundle
    - .:/app
    # - vite_dev:/app/public/vite-dev
    # - vite_test:/app/public/vite-test

services:
  web:
    <<: *app_base
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mailhog
    command: sh ./docker/start.sh

  # worker:
  #   <<: *app_base
  #   command: sh ./docker/start_worker.sh
  #   depends_on:
  #     - web

  # vite:
  #   <<: *app_base
  #   command: sh ./docker/start_assets.sh
  #   depends_on:
  #     - web
  #   ports:
  #     - "3036:3036"

  mailhog:
    image: mailhog/mailhog
    entrypoint: ["/bin/sh", "-c", "MailHog &>/dev/null"]
    ports:
      - "1025:1025"
      - "8025:8025"

  postgres:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  bundle_cache:
  postgres:
  s3:
  # vite_dev:
  # vite_test:
