version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - bundle_cache:/bundle
    command: sh ./docker/start.sh
  redis:
    image: redis
  postgres:
    image: postgres
    ports:
      - "5432:5432"

volumes:
  bundle_cache:
