version: '3'

services:
  web:
    build: .
    command: rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres
    ports:
      - "5432:5432"
  box:
    image: busybox
    volumes:
      - /bundle
