version: '3.1'
# Enable `worker` & `redis` containers support asycronous workers
# Enable `stripe` container when procesing payments
# Enable `localstack` container for aws support

services:
  web: &app_base
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      # - redis
      # - localstack
      # - stripe
    environment:
      - DOCKER_CONTAINER=1
    volumes:
      - bundle_cache:/bundle
      - .:/app
    command: sh ./docker/start.sh
  # worker:
  #   <<: *app_base
  #   command: sh ./docker/start_worker.sh
  #   ports: []
  #   depends_on:
  #     - web
  # redis:
  #   image: redis
  #   command: redis-server --appendonly yes
  #   volumes:
  #   # Enable the redis volume under volumes
  #   - redis:/data
  # localstack:
  #   image: localstack/localstack
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  # # SWITCH MYSQL: Disable postgres above and enable MySQL below
  # mysql:
  #   image: mysql:5.7
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=mysql
  #   volumes:
  #     - mysql:/var/lib/mysql
  # stripe:
  #   image: jheth/stripe-mock

volumes:
  bundle_cache:
  postgres:
  # redis:
