version: '3.8'
# Enable `worker` & `redis` containers support asycronous workers
# Enable `stripe` container when procesing payments
# Enable `localstack` container for aws support

services:
  web: &app_base
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      # - redis
      # - localstack
      # - stripe
    environment:
      - DOCKER_CONTAINER=1
    volumes:
      - bundle_cache:/bundle
      - .:/app
    command: sh ./docker/start.sh
  # worker:
  #   <<: *app_base
  #   command: sh ./docker/start_worker.sh
  #   ports: []
  #   depends_on:
  #     - web
  # redis:
  #   image: redis
  #   command: redis-server --appendonly yes
  #   volumes:
  #   # Enable the redis volume under volumes
  #   - redis:/data
  # localstack:
  #   image: localstack/localstack
  postgres:
    image: postgres
    environment:
      -  POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  bundle_cache:
  postgres:
  # redis:
